apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
  metadata:
  labels:
  app: fastapi
  spec:
  containers:
    - name: fastapi
  image: my-fastapi:latest
  ports:
    - containerPort: 8000
  env:
    - name: MONGODB_URL
  value: "mongodb://mongo:27017"
