apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue
  template:
  metadata:
  labels:
  app: vue
  spec:
  containers:
    - name: vue
  image: my-vue:latest
  ports:
    - containerPort: 80
