[project]
name = "duck-db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.3"
dependencies = [
    "dotenv==0.9.9",
    "duckdb==1.3.2",
    "pandas==2.3.1",
    "pymongo==4.10.1",
]
